# WARNING: If you are using on Intuition Docker, comment out all the secrets.
version: '3.8'

services:
  
  pidc:
    build: 
        context: ./pidc
        dockerfile: Dockerfile
    restart: always
    user: gennifer_user
    ports:
        - 5004:5000
    secrets:
        - gennifer_key
    environment:
        - SECRET_KEY_FILE=/run/secrets/gennifer_key
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
          #command: gunicorn -c gunicorn.config.py -b 0.0.0.0:5000 'pidc:create_app()'
    command: flask --app pidc run --debug --host 0.0.0.0
    depends_on:
        - redis
 
  worker-pidc:
    build: 
        context: ./pidc
        dockerfile: Dockerfile
    command: celery --app pidc.tasks.celery worker -Q pidc --loglevel=info
    environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
        - pidc
        - redis
 
  grisli:
    build: 
        context: ./grisli
        dockerfile: Dockerfile
    restart: always
    user: gennifer_user
    ports:
        - 5004:5000
    secrets:
        - gennifer_key
    environment:
        - SECRET_KEY_FILE=/run/secrets/gennifer_key
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
        - PYTHONUNBUFFERED=1
          #command: gunicorn -c gunicorn.config.py -b 0.0.0.0:5000 'pidc:create_app()'
    command: flask --app grisli run --debug --host 0.0.0.0
    depends_on:
        - redis

  worker-grisli:
    build: 
        context: ./grisli
        dockerfile: Dockerfile
    command: celery --app grisli.tasks.celery worker -Q grisli --loglevel=info
    environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
        - PYTHONUNBUFFERED=1
    depends_on:
        - grisli
        - redis

  genie3:
    build:
        context: ./genie3
        dockerfile: Dockerfile
    restart: always
    user: gennifer_user
    ports:
        - 5004:5000
    secrets:
        - gennifer_key
    environment:
        - SECRET_KEY_FILE=/run/secrets/gennifer_key
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
          #command: gunicorn -c gunicorn.config.py -b 0.0.0.0:5000 'genie3:create_app()'
    command: flask --app genie3 run --debug --host 0.0.0.0
    depends_on:
        - redis

  worker-genie3:
    build:
        context: ./genie3
        dockerfile: Dockerfile
    command: celery --app genie3.tasks.celery worker -Q genie3 --loglevel=info
    environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
        - genie3
        - redis

  grnboost2:
    build:
        context: ./grnboost2
        dockerfile: Dockerfile
    restart: always
    user: gennifer_user
    ports:
        - 5004:5000
    secrets:
        - gennifer_key
    environment:
        - SECRET_KEY_FILE=/run/secrets/gennifer_key
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
          #command: gunicorn -c gunicorn.config.py -b 0.0.0.0:5000 'grnboost2:create_app()'
    command: flask --app grnboost2 run --debug --host 0.0.0.0
    depends_on:
        - redis

  worker-grnboost2:
    build:
        context: ./grnboost2
        dockerfile: Dockerfile
    command: celery --app grnboost2.tasks.celery worker -Q grnboost2 --loglevel=info
    environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
        - grnboost2
        - redis
  
  bkb-grn:
    build:
        context: ./bkb-grn
        dockerfile: Dockerfile
    restart: always
    user: gennifer_user
    ports:
        - 5005:5000
    secrets:
        - gennifer_key
    environment:
        - PYTHONUNBUFFERED=1
        - SECRET_KEY_FILE=/run/secrets/gennifer_key
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
          #command: gunicorn -c gunicorn.config.py -b 0.0.0.0:5000 'grnboost2:create_app()'
    command: flask --app bkb_grn run --debug --host 0.0.0.0
    depends_on:
        - redis

  worker-bkb-grn:
    build:
        context: ./bkb-grn
        dockerfile: Dockerfile
    secrets:
        - gurobi_lic
    command: celery --app bkb_grn.tasks.celery worker -Q bkb_grn --loglevel=info
    environment:
        - PYTHONUNBUFFERED=1
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
        - GRB_LICENSE_FILE=/run/secrets/gurobi_lic
    depends_on:
        - bkb-grn
        - redis

  redis:
    image: redis:6-alpine

secrets:
  gennifer_key:
    file: secrets/gennifer/secret_key.txt
  gurobi_lic:
    file: secrets/gennifer/gurobi.lic
