# WARNING: If you are using on Intuition Docker, comment out all the secrets.
version: '3.8'

services:
  
  pidc:
    build: 
        context: ./pidc
        dockerfile: Dockerfile
    restart: always
    user: gennifer_user
    ports:
        - 5004:5000
    secrets:
        - gennifer_key
    environment:
        - SECRET_KEY_FILE=/run/secrets/gennifer_key
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
          #command: gunicorn -c gunicorn.config.py -b 0.0.0.0:5000 'pidc:create_app()'
    command: flask --app pidc run --debug --host 0.0.0.0
    depends_on:
        - redis
 
  worker-pidc:
    build: 
        context: ./pidc
        dockerfile: Dockerfile
    command: celery --app pidc.tasks.celery worker -Q pidc --loglevel=info
    environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
        - pidc
        - redis
 
  grisli:
    build: 
        context: ./grisli
        dockerfile: Dockerfile
    restart: always
    user: gennifer_user
    ports:
        - 5004:5000
    secrets:
        - gennifer_key
    environment:
        - SECRET_KEY_FILE=/run/secrets/gennifer_key
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
        - PYTHONUNBUFFERED=1
          #command: gunicorn -c gunicorn.config.py -b 0.0.0.0:5000 'pidc:create_app()'
    command: flask --app grisli run --debug --host 0.0.0.0
    depends_on:
        - redis

  worker-grisli:
    build: 
        context: ./grisli
        dockerfile: Dockerfile
    command: celery --app grisli.tasks.celery worker -Q grisli --loglevel=info
    environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
        - PYTHONUNBUFFERED=1
    depends_on:
        - grisli
        - redis

  redis:
    image: redis:6-alpine

secrets:
  gennifer_key:
    file: secrets/gennifer/secret_key.txt
